package moe.cuteyuki.kanadebot

import moe.cuteyuki.kanadebot.mainetwork.beans.MusicLevel
import moe.cuteyuki.kanadebot.mainetwork.beans.UserRatingData
import moe.cuteyuki.kanadebot.managers.ResourceManager
import moe.cuteyuki.kanadebot.utils.ImageBuilder
import java.awt.Color
import java.awt.Font
import java.awt.RenderingHints
import java.io.File
import javax.imageio.ImageIO

fun main(){
    ResourceManager.initialize()
    //TODO:Generate b50 image logic using userPreviewData.
    val avatarImage = ImageIO.read(File(ResourceManager.iconImagePath("405601")))
    val backgroundImage = ImageIO.read((object{}::class as Any).javaClass.getResourceAsStream("/base.png"))
    val qrCodeImage = ImageIO.read((object{}::class as Any).javaClass.getResourceAsStream("/qrcode.png"))
    val g2d = backgroundImage.createGraphics()
    val userName = "Yuki"
    val botName = "KanadeBot"

    g2d.setRenderingHint(
        RenderingHints.KEY_ANTIALIASING,
        RenderingHints.VALUE_ANTIALIAS_ON
    )

    g2d.setRenderingHint(
        RenderingHints.KEY_TEXT_ANTIALIASING,
        RenderingHints.VALUE_TEXT_ANTIALIAS_ON
    )

    g2d.setRenderingHint(
        RenderingHints.KEY_RENDERING,
        RenderingHints.VALUE_RENDER_QUALITY
    )

    //user avatar
    g2d.drawImage(avatarImage, 115, 83, null)

    //username
    g2d.color = Color(61, 61, 61)
    g2d.font = Font("MiSans-Bold", Font.PLAIN, 48)
    g2d.drawString(userName, 260, 165)

    //render b35+b15 = b50
    //due we dont use dispose so we can just use the last color to render this str.
    g2d.font = Font("MiSans-Regular", Font.PLAIN, 24)
    g2d.drawString("B35:9289 + B15:3869 = 13158", 260, 200)

    //render qrcode image & footer.
    g2d.drawImage(qrCodeImage,1610, 1410, 64, 64, null)
    g2d.drawString("Generated by ${botName}. UI designed by chuxuehaocai.", 70, 1430)
    g2d.drawString("https://github.com/chuxuehaocai/KanadeBot      (or scan the qrcode at ->", 70, 1460)

    val startXOffset = 65;
    val startYOffset = 350;
    var xCount = 0;
    var yCount = 0;
    //drawCards.
    for (i in 0..50) {
        if(xCount == 5) {
            yCount++
            xCount = 0;
        }
        if(yCount != 3) {
            ImageBuilder.drawRatingCard(
                g2d,
                UserRatingData(
                    musicName = "Freak Out Hr.",
                    level = MusicLevel.Master,
                    achievement = 1010000,
                    musicId = 11700
                ),
                startXOffset + (320 * xCount),
                startYOffset + (120 * yCount)
            )
        }else{
            ImageBuilder.drawRatingCard(
                g2d,
                UserRatingData(
                    musicName = "Freak Out Hr.",
                    level = MusicLevel.Master,
                    achievement = 1010000,
                    musicId = 11700
                ),
                startXOffset + (320 * xCount),
                1007 + (120 * yCount)
            )
        }
        xCount++
    }
    ImageIO.write(backgroundImage, "png", File("b50"+".png"))
}