package moe.cuteyuki.kanadebot

import moe.cuteyuki.kanadebot.mainetwork.beans.MusicLevel
import moe.cuteyuki.kanadebot.mainetwork.beans.UserRatingData
import moe.cuteyuki.kanadebot.managers.ResourceManager
import moe.cuteyuki.kanadebot.utils.ImageBuilder
import java.awt.Color
import java.awt.Font
import java.awt.RenderingHints
import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO

fun main() {
    ResourceManager.initialize()

    val avatarImage = ImageIO.read(File(ResourceManager.iconImagePath("405601")))
    val backgroundImage = ImageIO.read(
        (object{}::class as Any).javaClass.getResourceAsStream("/base.png")
    )
    //val backgroundImage = BufferedImage(1762, 1850, 1)
    val qrCodeImage = ImageIO.read(
        (object{}::class as Any).javaClass.getResourceAsStream("/qrcode.png")
    )
    val g2d = backgroundImage.createGraphics()
    val userName = "Yuki"
    val botName = "KanadeBot"

    g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON)
    g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON)
    g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY)

    // 用户头像
    g2d.drawImage(avatarImage, 115, 110, null)

    // 用户名
    g2d.color = Color(61, 61, 61)
    g2d.font = Font("MiSans-Bold", Font.PLAIN, 48)
    g2d.drawString(userName, 260, 175)

    // B35 + B15 = total
    g2d.font = Font("MiSans-Regular", Font.PLAIN, 24)
    g2d.drawString("B35:9289 + B15:3869 = 13158", 260, 215)

    // 底部二维码和文字
    g2d.drawImage(qrCodeImage, 1570, 1685, 128, 128, null)
    g2d.drawString("Generated by $botName. UI designed by chuxuehaocai.", 70, 1740)
    g2d.drawString("https://github.com/chuxuehaocai/KanadeBot      (or scan the qrcode at ->", 70, 1770)

    // 绘制 50 张卡片: B35 (rows 0–6) + B15 (rows 7–9, y=1220起)
    val startXOffset = 65
    val startYOffset = 350
    val b15StartYOffset = 1250
    val cardWidth = 320
    val cardHeight = 120
    val cardsPerRow = 5
    val b35Rows = 7

    for (i in 0 until 50) {
        val x = startXOffset + (cardWidth * (i % cardsPerRow))
        val row = i / cardsPerRow
        val y = if (row < b35Rows) {
            startYOffset + (cardHeight * row)
        } else {
            b15StartYOffset + (cardHeight * (row - b35Rows))
        }

        ImageBuilder.drawRatingCard(
            g2d,
            UserRatingData(
                musicName = "Freak Out Hr.",
                level = MusicLevel.Expert,
                achievement = 1010000,
                musicId = 11700
            ),
            x,
            y
        )
    }

    g2d.dispose()
    ImageIO.write(backgroundImage, "png", File("b50.png"))
}
